-- ==================================================================
-- 003_disable_m15_grinder.sql  |  OBSOLETA. No ejecutar.
-- ==================================================================
-- Esta migracion apagaba el flag `use_grinder` de la fila bot_id='m15'.
-- Ya no hace falta: el scalper embebido se ELIMINO del codigo del Sentinel
-- (bot/strategy.py), no solo se desactivo. Ver el commit
-- "refactor(m15): extrae por completo el grinder del Sentinel".
--
-- `bot_config.use_grinder` queda como columna muerta para la fila m15: el
-- motor ya no la lee. Se conserva la columna para no romper el dashboard ni
-- el historico; se puede borrar mas adelante con un ALTER TABLE ... DROP.
--
-- ------------------------------------------------------------------
-- LO QUE SIGUE ABIERTO Y SI IMPORTA: a que apunta el Healer.
-- ------------------------------------------------------------------
-- Quitar el grinder le quita al Healer su principal fuente de presupuesto
-- dentro de un ciclo perdedor (los bankings del Unwind estan congelados
-- mientras el ciclo va en negativo). Eso lo deja casi inerte, pero es una
-- mitigacion INDIRECTA: no arregla su seleccion de objetivo.
--
-- Evidencia de produccion (user e8d840ab-…, 21 amputaciones):
--   16 de 21 (76%) mordieron un `Hedge Lock`, a 0.01 lotes por vez.
--   El ticket #1609321275 (Hedge Lock) fue amputado 12 veces en 2h30m.
--   El ticket #1599444276 (Hedge Lock BUY @ 4046.36) se mordio con el
--   precio en ~3985: la cesta iba a favor y el hedge era el UNICO leg
--   contra-direccional, luego el minimo por construccion.
--
-- Causa: `_apply_healing` es un argmin(profit+swap) sin noción de rol. No
-- distingue entrada, cobertura, recovery ni rescate. Y como recovery/rescate
-- abren del lado de Op1, la cesta acumula N legs de un lado y UNO solo del
-- otro -> en cuanto la tendencia acompaña, el hedge es el peor leg siempre.
--
-- Ademas cada amputacion realiza en perdida ~90% del verde acumulado
-- (`budget = profit_available * 0.90`), asi que convertia los +30/+35 que
-- bancaba el Unwind en perdida realizada casi 1:1.
--
-- Arreglo pendiente de decision: prohibir al Healer amputar el leg de
-- cobertura mientras exista un perdedor core desnudo del lado opuesto.
-- Corresponde a la "via (d) no implementada" de
-- docs/memory/healer-unwind-hedge-cascade.md. No choca con "no stops duros":
-- no es poner un stop, es no cerrar la cobertura.
-- ==================================================================

-- (sin sentencias: nada que ejecutar)
